# Generated by Django 3.2.2 on 2022-02-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220224_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rename_me_later',
            new_name='author',
        ),
    ]
